events {
  worker_connections 1024;
}

http {
  upstream devenv1 {
    server devenv:8080;
  }

  upstream devenv2 {
    server devenv:5000;
  }

  server {
    listen 80;

    location /babylon {
      proxy_pass http://devenv1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /procgen {
      proxy_pass http://devenv2;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
  
